[package]
name = "task-tracker-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
json = "0.12.4"
prettytable-rs = "0.10.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

